@startuml UseCase
User --> (Browse catalogue)
User --> (Add item to shopping cart)
User --> (View cart)
User --> (Update cart)
User --> (View product page)
User --> (Checkout cart)
User --> (Make payment)
User --> (View account details)
User --> (View order history)
User --> (Update account details)

:Admin: ---> (Reviews orders) 
:Admin: ---> (Cancel orders) 
@enduml