@startuml Sequence

mainframe admin - dismiss flags

title "Admin - Dismiss Flags Diagram"
actor Admin
participant ServiceService
participant UserService
database db

group services

activate Admin
Admin -> ServiceService : DismissFlags(serviceId)
activate ServiceService
ServiceService -> db : dismissFlags(FlagStatus.inactive, FlagType.service, serviceId)
activate db
db -> ServiceService: success
deactivate db
ServiceService -> Admin: success
deactivate ServiceService

end group

group users

Admin -> UserService : DismissFlags(userId)
activate UserService
UserService -> db : dismissFlags(FlagStatus.inactive, FlagType.user, userId)
activate db
db -> UserService: success
deactivate db
UserService -> Admin: success
deactivate UserService
deactivate Admin

end group


@enduml