@startuml Sequence

mainframe flag user
title "Flag User & Service"
actor User
participant UserService
database db

group flag user
activate User

User -> UserService: flagUser(userId)
activate UserService
UserService -> db: findById(serviceId)
activate db
db -> UserService: user
deactivate db
UserService -> db: findFlagByFlaggingUserAndFlaggedEntityAndType(loggedInUserId, toFlagUserId, FlagType.user)
activate db
db -> UserService: flag
deactivate db

alt requested flag doesn't exists
    UserService -> db: save(flag)
    activate db
    db --> UserService: ok
    deactivate db
    UserService -> User: flag
else requested flag exists
    UserService -> User: already flagged user error
    deactivate UserService
end
end group

@enduml
