@startuml Sequence

mainframe admin - feature service

title "Admin - Feature Service Diagram"
actor Admin
participant ServiceService
database db

group feature service

activate Admin
Admin -> ServiceService : FeatureService(serviceId)
activate ServiceService
ServiceService -> db :findFeatured()
db -> ServiceService: featured services
deactivate db
note right of ServiceService
 max feature count = 3
end note
alt featured services count is already 3
    ServiceService -> Admin: featured count error
else

ServiceService -> db :findServiceById(serviceId)
activate db
db -> ServiceService: service
deactivate db
alt service found
    ServiceService -> Admin: featured service
else service not found
    ServiceService -> Admin: service not found error
deactivate ServiceService
end
end
end group





@enduml